// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v3.11.4
// source: github.com/gogo/protobuf/gogoproto/gogo.proto

/* eslint-disable */

export const protobufPackage = "gogoproto";
