name: buildx-lab-releases-json

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches:
      - 'main'
  pull_request:
    paths:
      - '.github/workflows/buildx-lab-releases-json.yml'

jobs:
  generate:
    uses: crazy-max/.github/.github/workflows/releases-json.yml@7f83a5a887650a38e4d0e05d5262309cfaa31459
    with:
      repository: docker/buildx-desktop
      artifact_name: buildx-lab-releases-json
      filename: buildx-lab-releases.json
    secrets: inherit

  open-pr:
    runs-on: ubuntu-24.04
    if: github.event_name != 'pull_request'
    needs:
      - generate
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Download
        uses: actions/download-artifact@v5
        with:
          name: buildx-lab-releases-json
          path: .github
      -
        name: Commit changes
        run: |
          git add -A .
      -
        name: Create PR
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f  # v7.0.5
        with:
          base: main
          branch: bot/buildx-lab-releases-json
          commit-message: "github: update .github/buildx-lab-releases.json"
          signoff: true
          delete-branch: true
          title: "Update `.github/buildx-lab-releases.json`"
          body: |
            Update `.github/buildx-lab-releases.json` to keep in sync with [https://github.com/docker/buildx-desktop](https://github.com/docker/buildx-desktop).
          draft: false
