name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'
  pull_request:
    paths-ignore:
      - '.github/*-releases.json'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 20
          - 18
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Build
        uses: docker/bake-action@v5
        with:
          targets: build
        env:
          NODE_VERSION: ${{ matrix.node_version }}
