name: compose-releases-json

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches:
      - 'main'
  pull_request:
    paths:
      - '.github/workflows/compose-releases-json.yml'

jobs:
  generate:
    uses: crazy-max/.github/.github/workflows/releases-json.yml@9791b02439e3c95de89d128a625169ceee56dc55
    with:
      repository: docker/compose
      artifact_name: compose-releases-json
      filename: compose-releases.json
    secrets: inherit

  open-pr:
    runs-on: ubuntu-24.04
    if: github.event_name != 'pull_request'
    needs:
      - generate
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Download
        uses: actions/download-artifact@v5
        with:
          name: compose-releases-json
          path: .github
      -
        name: Commit changes
        run: |
          git add -A .
      -
        name: Create PR
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e  # v7.0.8
        with:
          base: main
          branch: bot/compose-releases-json
          commit-message: "github: update .github/compose-releases.json"
          signoff: true
          delete-branch: true
          title: "Update `.github/compose-releases.json`"
          body: |
            Update `.github/compose-releases.json` to keep in sync with [https://github.com/docker/compose](https://github.com/docker/compose).
          draft: false
